name: tests
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
jobs:
  call-deps:
    uses: jhunufernandes/python-github-actions/.github/workflows/deps.yml@main
    with:
      pip_args: tests
  call-tests:
    needs:
      - call-deps
    uses: jhunufernandes/python-github-actions/.github/workflows/tests.yml@main
    with:
      pip_args: tests